[viam]
image=ghcr.io/ublue-os/fedora-toolbox:latest
pull=true

# VSCodium repo
pre_init_hooks="base64 -d > /etc/yum.repos.d/vscodium.repo <<< 'W2dpdGxhYi5jb21fcGF1bGNhcnJvdHlfdnNjb2RpdW1fcmVwb10KbmFtZT1naXRsYWIuY29tX3BhdWxjYXJyb3R5X3ZzY29kaXVtX3JlcG8KYmFzZXVybD1odHRwczovL3BhdWxjYXJyb3R5LmdpdGxhYi5pby92c2NvZGl1bS1kZWItcnBtLXJlcG8vcnBtcy8KZW5hYmxlZD0xCmdwZ2NoZWNrPTEKcmVwb19ncGdjaGVjaz0xCmdwZ2tleT1odHRwczovL2dpdGxhYi5jb20vcGF1bGNhcnJvdHkvdnNjb2RpdW0tZGViLXJwbS1yZXBvL3Jhdy9tYXN0ZXIvcHViLmdwZwptZXRhZGF0YV9leHBpcmU9MWgKCg=='"

# additional_packages doesn't support package groups
init_hooks="dnf group install -y c-development"

# rdk cgo deps
additional_packages="x264-devel NLopt-devel"

# extra cli tools
additional_packages="picocom"
exported_bins="/usr/bin/picocom"

# extra gui apps
additional_packages="codium"
exported_apps="codium"
