[workspace]
authors = ["Joshua Matthews <josh.matthews@viam.com>"]
channels = ["conda-forge"]
name = "viam-workspace"
platforms = ["linux-64"]
version = "0.1.0"

[activation.env]
PKG_CONFIG_PATH = "$CONDA_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"

[tasks]

[dependencies]
nlopt = ">=2.10.0,<3"
x264 = ">=1!164.3095,<1!165"
